debug: False

output_path:
pretrained_model:
device_id: [ 0 ]
cuda_visible_device: '0'

# loss_function
loss: 'cross_entropy'

data_param:
  type: "UT_HAR"
  class_num: 7
  batch_size: 1
  workers: 0
  pin_memory: False
  drop_last: True
  dataset_mode: [ "train", "val" ]

  train_data_param:
    data_path: /media/sda/LeiH/Dataset/UT_HAR/data
    label_path: /media/sda/LeiH/Dataset/UT_HAR/label
  val_data_param:
    data_path: /media/sda/LeiH/Dataset/UT_HAR/data
    label_path: /media/sda/LeiH/Dataset/UT_HAR/label

# model
model_param:
  type: 'UT_HAR_LSTM'
  input_T: 250
  input_S: 90
  hidden_dim: 128
  num_layers: 1

# head_param is for build_head
head_param:
  type: 'SimpleHead'
  num_classes: 7
  in_channels: 128


# optimizer_param is for build_optimizer
optimizer_param:
  optim_type: 'adam'
  lr: 0.001
  wd: 0


# training_param is for class TrainingEngine
training_param:
  dataloader_datatype: 'N1TW'
  model_datatype: 'NTW'
  max_epoch: 100
  val_frequency: 1
  save_frequency: 1





