debug: False

output_path:
pretrained_model:
device_id: [ 0 ]
cuda_visible_device: '0'

# loss_function
loss: 'cross_entropy'

data_param:
  type: "UT_HAR"
  class_num: 7
  batch_size: 16
  workers: 0
  pin_memory: False
  drop_last: True
  dataset_mode: [ "train", "val" ]

  train_data_param:
    data_path: /media/sda/LeiH/Dataset/UT_HAR/data
    label_path: /media/sda/LeiH/Dataset/UT_HAR/label
  val_data_param:
    data_path: /media/sda/LeiH/Dataset/UT_HAR/data
    label_path: /media/sda/LeiH/Dataset/UT_HAR/label

# model_param is for build_model
model_param:
  type: 'STGCN'
  in_channels: 30
  base_channels: 64
  data_bn_type: "VC"
  ch_ratio: 2
  num_person: 1
  num_stages: 10
  inflate_stages: [ 5,8 ]
  down_stages: [ 5,8 ]
  graph_cfg:
    layout: 'antenna_graph'

# head_param is for build_head
head_param:
  type: 'GCNHead'
  num_classes: 7
  in_channels: 256

# optimizer_param is for build_optimizer
optimizer_param:
  optim_type: 'adam'
  lr: 0.0001
  wd: 0

# training_param is for class TrainingEngine
training_param:
  dataloader_datatype: 'N1TW'
  model_datatype: 'N1T3S'
  max_epoch: 100
  val_frequency: 1
  save_frequency: 1



