debug: False

output_path:
pretrained_model:
device_id: [ 0 ]
cuda_visible_device: '0'

# loss_function
loss: 'cross_entropy'

data_param:
  type: 'MMFi'
  dataset_root: /media/sda/datasets/MMFi_Dataset/data_unzip
  modality: wifi-csi


  protocol: protocol1

  data_unit: sequence
#  data_unit: frame
  random_split:
    ratio: 0.8
    random_seed: 0
    train_dataset:
      split: training
      scenes: None
      subjects: None
      actions: all
    val_dataset:
      split: validation
      scenes: None
      subjects: None
      actions: all

  cross_scene_split:
    train_dataset:
      split: training
      scenes: [ E01, E02, E03 ]
      subjects: None
      actions: all
    val_dataset:
      split: validation
      scenes: [ E04 ]
      subjects: None
      actions: all

  cross_subject_split:
    train_dataset:
      split: training
      scenes: None
      subjects: [ S01, S02, S03, S04, S06, S07, S08, S09, S11, S12, S13, S14, S16, S17, S18, S19, S21, S22, S23, S24, S26, S27, S28, S29, S31, S32, S33, S34, S36, S37, S38, S39 ]
      actions: all
    val_dataset:
      split: validation
      scenes: None
      subjects: [ S05, S10, S15, S20, S25, S30, S35, S40 ]
      actions: all

  manual_split:
    train_dataset:
      split: training
      scenes: None
      subjects: [ S01, S02, S03, S04, S05, S06, S07, S08, S09, S10, S11, S12, S13, S14, S15, S16, S17, S18, S19, S20, S21, S22, S23, S24, S25, S26, S27, S28, S29, S30, S31, S32, S33, S34, S35, S36, S37, S38, S39, S40 ]
      actions: [ A01, A02, A03, A04, A05, A06, A07, A08, A09, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20, A21 ]
    val_dataset:
      split: validation
      scenes: None
      subjects: [ S01, S02, S03, S04, S05, S06, S07, S08, S09, S10, S11, S12, S13, S14, S15, S16, S17, S18, S19, S20, S21, S22, S23, S24, S25, S26, S27, S28, S29, S30, S31, S32, S33, S34, S35, S36, S37, S38, S39, S40 ]
      actions: [ A22, A23, A24, A25, A26, A27 ]

  split_to_use: cross_subject_split

  init_rand_seed: 0
  train_loader:
    batch_size: 32
  validation_loader:
    batch_size: 1

# model_param is for build_model
model_param:
  type: 'STGCN'
  in_channels: 114
  base_channels: 114
  data_bn_type: "VC"
  ch_ratio: 2
  num_person: 1
  num_stages: 10
  inflate_stages: [5,8]
  down_stages: [5,8]
  graph_cfg:
    layout: 'antenna_graph'

# head_param is for build_head
head_param:
  type: 'GCNHead'
  num_classes: 14
  in_channels: 456

# optimizer_param is for build_optimizer
optimizer_param:
  optim_type: 'adam'
  lr: 0.0001
  wd: 0.01

# training_param is for class TrainingEngine
training_param:
  dataloader_datatype: 'NAST'
  model_datatype: 'N1TAS'
  max_epoch: 100
  val_frequency: 1
  save_frequency: 1



